namespace StockSharp.Algo.Risk;

/// <summary>
/// The interface, describing risks control manager.
/// </summary>
public interface IRiskManager : ILogSource, IPersistable, ICloneable<IRiskManager>
{
	/// <summary>
	/// Rule list.
	/// </summary>
	INotifyList<IRiskRule> Rules { get; }

	/// <summary>
	/// To reset the state.
	/// </summary>
	void Reset();

	/// <summary>
	/// To process the trade message.
	/// </summary>
	/// <param name="message">The trade message.</param>
	/// <returns>List of rules, activated by the message.</returns>
	IEnumerable<IRiskRule> ProcessRules(Message message);

	/// <summary>
	/// Seeds this manager's circuit-breaker <see cref="Rules"/> from the canonical, single-source-of-truth
	/// <see cref="RiskLimitSet"/> using the default <see cref="RiskActions.ClosePositions"/> action, so
	/// every threshold enforced here is defined exactly once and matches the per-order pre-trade gate. This
	/// is the production configuration entry point exposed through the abstraction; it is a convenience
	/// overload of <see cref="ApplyCanonicalLimits(RiskLimitSet, RiskActions)"/>. Only rules previously
	/// generated by a canonical apply are replaced; unrelated rules are preserved.
	/// </summary>
	/// <param name="limits">The canonical limit set to seed from. Cannot be null.</param>
	/// <exception cref="ArgumentNullException"><paramref name="limits"/> is <see langword="null"/>.</exception>
	/// <exception cref="ArgumentException">The frequency pair is malformed.</exception>
	void ApplyCanonicalLimits(RiskLimitSet limits);

	/// <summary>
	/// Seeds this manager's circuit-breaker <see cref="Rules"/> from the canonical, single-source-of-truth
	/// <see cref="RiskLimitSet"/>, assigning <paramref name="action"/> to every generated rule. The
	/// replacement set is built in full and swapped in atomically relative to <see cref="ProcessRules"/>,
	/// and only rules previously generated by a canonical apply are replaced; unrelated rules are preserved.
	/// </summary>
	/// <param name="limits">The canonical limit set to seed from. Cannot be null.</param>
	/// <param name="action">The circuit-breaker action assigned to every generated rule.</param>
	/// <exception cref="ArgumentNullException"><paramref name="limits"/> is <see langword="null"/>.</exception>
	/// <exception cref="ArgumentException">The frequency pair is malformed.</exception>
	void ApplyCanonicalLimits(RiskLimitSet limits, RiskActions action);
}